#!/usr/bin/python3

"""
This is a sample module for the AirBnB_clone project.
It demonstrates the usage of classes and functions.
"""

def my_function():
	    """
		        This is a sample function within the module.
			    It prints a message to the console.
			           """
			           print("Hello, world!")


			       class MyClass:
				           """
						       This is a sample class within the module.
						           It defines a basic class with a single method.
						           """

						           def my_method(self):
								           """
										           This is a sample method within the class.
											           It prints a message to the console.
												          """
													         print("Hello from MyClass!")


														if __name__ == "__main__":
														    my_function()
	    obj = MyClass()
	    obj.my_method()
